name: Deploy Firebase Functions
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create .env file
        run: |
          echo "AWS_SECRET_KEY=$AWS_SECRET_KEY" >> ./functions/.env.prod
          echo "AWS_ACCESS_KEY=$AWS_ACCESS_KEY" >> ./functions/.env.prod
          echo "AWS_PLATFORM_ARN=$AWS_PLATFORM_ARN" >> ./functions/.env.prod

      - name: Deploy Firebase Functions
        run: |
          npm install -g firebase-tools
          firebase use prod
          firebase login:ci --no-localhost --token "$FIREBASE_TOKEN"
          firebase deploy --only functions
